name: veganstyle
favicon: null
layout_spectrum: 0.682825970929116
typography_spectrum: 0.56328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9a35a'
    - '#ffffff'
    - '#ff0000'
    - '#aa5555'
    - '#000000'
  brandStrength: 0.5242479117587209
  lightness: 0.24837200809270144
  saturation: 0.20682746195234358
  rhythmicContrast: 0.9901491329073906
purpose: []
